/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Forgot Password */
        post: operations["forgot_password_api_v1_auth_forgot_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Google Sign In */
        post: operations["google_sign_in_api_v1_auth_google_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/resend-verification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resend Verification */
        post: operations["resend_verification_api_v1_auth_resend_verification_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Password */
        post: operations["reset_password_api_v1_auth_reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Email */
        post: operations["verify_email_api_v1_auth_verify_email_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diseases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Diseases */
        get: operations["list_diseases_api_v1_diseases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_api_v1_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Plants */
        get: operations["list_plants_api_v1_plants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plants/{plant}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Plant */
        get: operations["read_plant_api_v1_plants__plant__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plants/{plant}/diseases/{disease}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Disease */
        get: operations["read_disease_api_v1_plants__plant__diseases__disease__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readyz */
        get: operations["readyz_api_v1_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scans */
        get: operations["list_scans_api_v1_scans_get"];
        put?: never;
        /** Create Scan */
        post: operations["create_scan_api_v1_scans_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scan Stats */
        get: operations["scan_stats_api_v1_scans_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Scan */
        get: operations["read_scan_api_v1_scans__scan_id__get"];
        put?: never;
        post?: never;
        /** Delete Scan */
        delete: operations["delete_scan_api_v1_scans__scan_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scan_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Feedback */
        put: operations["put_feedback_api_v1_scans__scan_id__feedback_put"];
        post?: never;
        /** Delete Feedback */
        delete: operations["delete_feedback_api_v1_scans__scan_id__feedback_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans/{scan_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Scan */
        post: operations["retry_scan_api_v1_scans__scan_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Me */
        get: operations["read_me_api_v1_users_me_get"];
        put?: never;
        post?: never;
        /** Delete Me */
        delete: operations["delete_me_api_v1_users_me_delete"];
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_api_v1_users_me_patch"];
        trace?: never;
    };
    "/api/v1/users/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password */
        post: operations["change_password_api_v1_users_me_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountDeletedOut */
        AccountDeletedOut: {
            /**
             * Deleted
             * @default true
             */
            deleted: boolean;
        };
        /** AuthSessionOut */
        AuthSessionOut: {
            /** Access Token */
            access_token: string;
            /** Expires In */
            expires_in: number;
            /**
             * Refresh Expires At
             * Format: date-time
             */
            refresh_expires_at: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserOut"];
        };
        /** Body_create_scan_api_v1_scans_post */
        Body_create_scan_api_v1_scans_post: {
            /** Image */
            image: string;
        };
        /** ChangePasswordIn */
        ChangePasswordIn: {
            /** Current Password */
            current_password?: string | null;
            /** New Password */
            new_password: string;
        };
        /** DeleteAccountIn */
        DeleteAccountIn: {
            /** Confirmation */
            confirmation?: string | null;
            /** Password */
            password?: string | null;
        };
        /** DiseaseDetailOut */
        DiseaseDetailOut: {
            /** Affected Species */
            affected_species: string[];
            /** Cause */
            cause: string | null;
            /** Display Name */
            display_name: string;
            /** Images */
            images: components["schemas"]["DiseaseImageOut"][];
            /** Name */
            name: string;
            /** Pathogen Name */
            pathogen_name: string | null;
            /** Pathogen Type */
            pathogen_type: string | null;
            plant: components["schemas"]["PlantRefOut"];
            /** Preventions */
            preventions: string[];
            /** Severity */
            severity: string | null;
            /** Slug */
            slug: string;
            /** Symptoms */
            symptoms: string[];
            /** Treatments */
            treatments: string[];
        };
        /** DiseaseImageOut */
        DiseaseImageOut: {
            /** Alt Text */
            alt_text: string | null;
            /** Url */
            url: string;
        };
        /** DiseaseListOut */
        DiseaseListOut: {
            /** Items */
            items: components["schemas"]["DiseaseSummaryOut"][];
        };
        /** DiseaseSummaryOut */
        DiseaseSummaryOut: {
            /** Display Name */
            display_name: string;
            /** Name */
            name: string;
            /** Pathogen Type */
            pathogen_type: string | null;
            /** Plant Name */
            plant_name: string;
            /** Plant Slug */
            plant_slug: string;
            /** Severity */
            severity: string | null;
            /** Slug */
            slug: string;
        };
        /** Envelope[AccountDeletedOut] */
        Envelope_AccountDeletedOut_: {
            data?: components["schemas"]["AccountDeletedOut"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Success */
            success: boolean;
        };
        /** Envelope[AuthSessionOut] */
        Envelope_AuthSessionOut_: {
            data?: components["schemas"]["AuthSessionOut"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Success */
            success: boolean;
        };
        /** Envelope[DiseaseDetailOut] */
        Envelope_DiseaseDetailOut_: {
            data?: components["schemas"]["DiseaseDetailOut"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Success */
            success: boolean;
        };
        /** Envelope[DiseaseListOut] */
        Envelope_DiseaseListOut_: {
            data?: components["schemas"]["DiseaseListOut"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Success */
            success: boolean;
        };
        /** Envelope[GoogleSessionOut] */
        Envelope_GoogleSessionOut_: {
            data?: components["schemas"]["GoogleSessionOut"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Success */
            success: boolean;
        };
        /** Envelope[HealthOut] */
        Envelope_HealthOut_: {
            data?: components["schemas"]["HealthOut"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Success */
            success: boolean;
        };
        /** Envelope[LogoutOut] */
        Envelope_LogoutOut_: {
            data?: components["schemas"]["LogoutOut"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Success */
            success: boolean;
        };
        /** Envelope[PasswordChangedOut] */
        Envelope_PasswordChangedOut_: {
            data?: components["schemas"]["PasswordChangedOut"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Success */
            success: boolean;
        };
        /** Envelope[PasswordResetOut] */
        Envelope_PasswordResetOut_: {
            data?: components["schemas"]["PasswordResetOut"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Success */
            success: boolean;
        };
        /** Envelope[PlantDetailOut] */
        Envelope_PlantDetailOut_: {
            data?: components["schemas"]["PlantDetailOut"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Success */
            success: boolean;
        };
        /** Envelope[PlantListOut] */
        Envelope_PlantListOut_: {
            data?: components["schemas"]["PlantListOut"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Success */
            success: boolean;
        };
        /** Envelope[RefreshOut] */
        Envelope_RefreshOut_: {
            data?: components["schemas"]["RefreshOut"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Success */
            success: boolean;
        };
        /** Envelope[ScanCreatedOut] */
        Envelope_ScanCreatedOut_: {
            data?: components["schemas"]["ScanCreatedOut"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Success */
            success: boolean;
        };
        /** Envelope[ScanDeletedOut] */
        Envelope_ScanDeletedOut_: {
            data?: components["schemas"]["ScanDeletedOut"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Success */
            success: boolean;
        };
        /** Envelope[ScanDetailOut] */
        Envelope_ScanDetailOut_: {
            data?: components["schemas"]["ScanDetailOut"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Success */
            success: boolean;
        };
        /** Envelope[ScanFeedbackOut] */
        Envelope_ScanFeedbackOut_: {
            data?: components["schemas"]["ScanFeedbackOut"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Success */
            success: boolean;
        };
        /** Envelope[ScanListOut] */
        Envelope_ScanListOut_: {
            data?: components["schemas"]["ScanListOut"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Success */
            success: boolean;
        };
        /** Envelope[ScanStatsOut] */
        Envelope_ScanStatsOut_: {
            data?: components["schemas"]["ScanStatsOut"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Success */
            success: boolean;
        };
        /** Envelope[SentOut] */
        Envelope_SentOut_: {
            data?: components["schemas"]["SentOut"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Success */
            success: boolean;
        };
        /** Envelope[UserOut] */
        Envelope_UserOut_: {
            data?: components["schemas"]["UserOut"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Success */
            success: boolean;
        };
        /** Envelope[VerifiedOut] */
        Envelope_VerifiedOut_: {
            data?: components["schemas"]["VerifiedOut"] | null;
            error?: components["schemas"]["ErrorBody"] | null;
            /** Success */
            success: boolean;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            }[] | null;
            /** Message */
            message: string;
            /** Request Id */
            request_id?: string | null;
        };
        /** ForgotPasswordIn */
        ForgotPasswordIn: {
            /** Email */
            email: string;
        };
        /** GoogleSessionOut */
        GoogleSessionOut: {
            /** Access Token */
            access_token: string;
            /** Expires In */
            expires_in: number;
            /** Is New User */
            is_new_user: boolean;
            /** Linked Existing Account */
            linked_existing_account: boolean;
            /**
             * Refresh Expires At
             * Format: date-time
             */
            refresh_expires_at: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserOut"];
        };
        /** GoogleSignInIn */
        GoogleSignInIn: {
            /** Code */
            code: string;
            /** Code Verifier */
            code_verifier: string;
            /** Nonce */
            nonce: string;
            /** Redirect Uri */
            redirect_uri: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
        };
        /** LoginIn */
        LoginIn: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** LogoutOut */
        LogoutOut: {
            /**
             * Revoked
             * @default true
             */
            revoked: boolean;
        };
        /** PasswordChangedOut */
        PasswordChangedOut: {
            /**
             * Changed
             * @default true
             */
            changed: boolean;
        };
        /** PasswordResetOut */
        PasswordResetOut: {
            /**
             * Reset
             * @default true
             */
            reset: boolean;
        };
        /** PlantDetailOut */
        PlantDetailOut: {
            /** Disease Count */
            disease_count: number;
            /** Diseases */
            diseases: components["schemas"]["DiseaseSummaryOut"][];
            /** Family */
            family: string | null;
            /** Image Alt */
            image_alt: string | null;
            /** Image Url */
            image_url: string | null;
            /** Light */
            light: string | null;
            /** Name */
            name: string;
            /** Plant Type */
            plant_type: string | null;
            /** Scientific Name */
            scientific_name: string | null;
            /** Slug */
            slug: string;
            /** Soil Type */
            soil_type: string | null;
            /** Temperature */
            temperature: string | null;
            /** Water Needs */
            water_needs: string | null;
        };
        /** PlantListOut */
        PlantListOut: {
            /** Items */
            items: components["schemas"]["PlantSummaryOut"][];
        };
        /** PlantRefOut */
        PlantRefOut: {
            /** Name */
            name: string;
            /** Slug */
            slug: string;
        };
        /** PlantSummaryOut */
        PlantSummaryOut: {
            /** Disease Count */
            disease_count: number;
            /** Family */
            family: string | null;
            /** Image Alt */
            image_alt: string | null;
            /** Image Url */
            image_url: string | null;
            /** Name */
            name: string;
            /** Plant Type */
            plant_type: string | null;
            /** Scientific Name */
            scientific_name: string | null;
            /** Slug */
            slug: string;
        };
        /** RefreshIn */
        RefreshIn: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** RefreshOut */
        RefreshOut: {
            /** Access Token */
            access_token: string;
            /** Expires In */
            expires_in: number;
            /** Refresh Expires At */
            refresh_expires_at: string | null;
            /** Refresh Token */
            refresh_token: string | null;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** RegisterIn */
        RegisterIn: {
            /** Email */
            email: string;
            /** First Name */
            first_name: string;
            /**
             * Last Name
             * @default
             */
            last_name: string;
            /** Password */
            password: string;
        };
        /** ResetPasswordIn */
        ResetPasswordIn: {
            /** New Password */
            new_password: string;
            /** Token */
            token: string;
        };
        /** ScanCreatedOut */
        ScanCreatedOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            stage: components["schemas"]["ScanStage"] | null;
            status: components["schemas"]["ScanStatus"];
        };
        /** ScanDeletedOut */
        ScanDeletedOut: {
            /** Deleted */
            deleted: boolean;
        };
        /** ScanDetailOut */
        ScanDetailOut: {
            /** Confidence */
            confidence: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            disease: components["schemas"]["ScanDiseaseOut"] | null;
            disease_detail: components["schemas"]["DiseaseDetailOut"] | null;
            /** Failure Code */
            failure_code: string | null;
            feedback: components["schemas"]["ScanFeedbackOut"] | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Image Expires At
             * Format: date-time
             */
            image_expires_at: string;
            /** Image Url */
            image_url: string;
            plant: components["schemas"]["PlantRefOut"] | null;
            stage: components["schemas"]["ScanStage"] | null;
            status: components["schemas"]["ScanStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            verdict: components["schemas"]["ScanVerdict"] | null;
        };
        /** ScanDiseaseOut */
        ScanDiseaseOut: {
            /** Display Name */
            display_name: string;
            /** Name */
            name: string;
            /** Severity */
            severity: string | null;
            /** Slug */
            slug: string;
        };
        /** ScanFeedbackIn */
        ScanFeedbackIn: {
            /** Comment */
            comment?: string | null;
            /** Correct Disease */
            correct_disease?: string | null;
            /** Correct Plant */
            correct_plant?: string | null;
            /** Is Correct */
            is_correct: boolean;
        };
        /** ScanFeedbackOut */
        ScanFeedbackOut: {
            /** Comment */
            comment: string | null;
            /** Correct Disease */
            correct_disease: string | null;
            /** Correct Plant */
            correct_plant: string | null;
            /** Is Correct */
            is_correct: boolean;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ScanListOut */
        ScanListOut: {
            /** Items */
            items: components["schemas"]["ScanSummaryOut"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /**
         * ScanStage
         * @enum {string}
         */
        ScanStage: "validating" | "analyzing" | "saving";
        /** ScanStatsOut */
        ScanStatsOut: {
            by_verdict: components["schemas"]["VerdictCountsOut"];
            /** Last 30 Days */
            last_30_days: number;
            /** Top Diseases */
            top_diseases: components["schemas"]["TopDiseaseOut"][];
            /** Total */
            total: number;
        };
        /**
         * ScanStatus
         * @enum {string}
         */
        ScanStatus: "processing" | "completed" | "failed";
        /** ScanSummaryOut */
        ScanSummaryOut: {
            /** Confidence */
            confidence: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            disease: components["schemas"]["ScanDiseaseOut"] | null;
            /** Failure Code */
            failure_code: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Image Expires At
             * Format: date-time
             */
            image_expires_at: string;
            /** Image Url */
            image_url: string;
            plant: components["schemas"]["PlantRefOut"] | null;
            stage: components["schemas"]["ScanStage"] | null;
            status: components["schemas"]["ScanStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            verdict: components["schemas"]["ScanVerdict"] | null;
        };
        /**
         * ScanVerdict
         * @enum {string}
         */
        ScanVerdict: "disease" | "healthy" | "unknown";
        /** SentOut */
        SentOut: {
            /**
             * Sent
             * @default true
             */
            sent: boolean;
        };
        /** TopDiseaseOut */
        TopDiseaseOut: {
            /** Count */
            count: number;
            /** Disease Name */
            disease_name: string;
            /** Disease Slug */
            disease_slug: string;
            /** Display Name */
            display_name: string;
            /** Plant Name */
            plant_name: string;
            /** Plant Slug */
            plant_slug: string;
        };
        /** UpdateProfileIn */
        UpdateProfileIn: {
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
        };
        /** UserOut */
        UserOut: {
            /** Auth Methods */
            auth_methods: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /** Email Verified */
            email_verified: boolean;
            /** Email Verified At */
            email_verified_at: string | null;
            /** First Name */
            first_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Name */
            last_name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VerdictCountsOut */
        VerdictCountsOut: {
            /** Disease */
            disease: number;
            /** Healthy */
            healthy: number;
            /** Unknown */
            unknown: number;
        };
        /** VerifiedOut */
        VerifiedOut: {
            /**
             * Verified
             * @default true
             */
            verified: boolean;
        };
        /** VerifyEmailIn */
        VerifyEmailIn: {
            /** Token */
            token: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    forgot_password_api_v1_auth_forgot_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ForgotPasswordIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_SentOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    google_sign_in_api_v1_auth_google_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleSignInIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_GoogleSessionOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_AuthSessionOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_LogoutOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_RefreshOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_AuthSessionOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resend_verification_api_v1_auth_resend_verification_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_SentOut_"];
                };
            };
        };
    };
    reset_password_api_v1_auth_reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_PasswordResetOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_email_api_v1_auth_verify_email_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_VerifiedOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_diseases_api_v1_diseases_get: {
        parameters: {
            query?: {
                q?: string | null;
                plant?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_DiseaseListOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_api_v1_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_HealthOut_"];
                };
            };
        };
    };
    list_plants_api_v1_plants_get: {
        parameters: {
            query?: {
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_PlantListOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_plant_api_v1_plants__plant__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plant: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_PlantDetailOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_disease_api_v1_plants__plant__diseases__disease__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plant: string;
                disease: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_DiseaseDetailOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readyz_api_v1_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_HealthOut_"];
                };
            };
        };
    };
    list_scans_api_v1_scans_get: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
                status?: components["schemas"]["ScanStatus"] | null;
                verdict?: components["schemas"]["ScanVerdict"] | null;
                plant?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ScanListOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_scan_api_v1_scans_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_scan_api_v1_scans_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ScanCreatedOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_stats_api_v1_scans_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ScanStatsOut_"];
                };
            };
        };
    };
    read_scan_api_v1_scans__scan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ScanDetailOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_scan_api_v1_scans__scan_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ScanDeletedOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_feedback_api_v1_scans__scan_id__feedback_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanFeedbackIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ScanFeedbackOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_feedback_api_v1_scans__scan_id__feedback_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ScanDeletedOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_scan_api_v1_scans__scan_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scan_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ScanCreatedOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_me_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_UserOut_"];
                };
            };
        };
    };
    delete_me_api_v1_users_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteAccountIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_AccountDeletedOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_me_api_v1_users_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_UserOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_password_api_v1_users_me_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_PasswordChangedOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
